### ISSUE TITLE
Numerous UCL style changes

### ISSUE THREAD

**Issue by owainkenwayucl** [UCL/RCPSTrainingMaterials#8]
Hi,

So we have a bunch of issues with the UCL style that we have for the slides.

These are:

1. We need to make the code blocks bigger.
2. We need to change the default transition to something plainer
3. Comments in code blocks should not be green on green!

Cheers,
Owain

**Comment by jamespjh** [comment]
slide theme.css 
``` css
.reveal pre code 
{
  font-size: 200%;
  line-height: 200%;
  background-color: #303030;
}
code > span.co 
{
  color: #FFFFFF;
}
```

Addresses #1 and #3
